=begin
#Assembly API

#Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.

The version of the OpenAPI document: 2.0
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for AssemblyRuby::MarketplacesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MarketplacesApi' do
  before do
    # run before each test
    @api_instance = AssemblyRuby::MarketplacesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplacesApi' do
    it 'should create an instance of MarketplacesApi' do
      expect(@api_instance).to be_instance_of(AssemblyRuby::MarketplacesApi)
    end
  end

  # unit tests for show_marketplace
  # Show Marketplace
  # Show details of your **Platform**, providing access to your configuration and related **User** and **Company**.
  # @param [Hash] opts the optional parameters
  # @return [Marketplace]
  describe 'show_marketplace test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
