=begin
#Assembly API

#Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.

The version of the OpenAPI document: 2.0
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for AssemblyRuby::ToolsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ToolsApi' do
  before do
    # run before each test
    @api_instance = AssemblyRuby::ToolsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ToolsApi' do
    it 'should create an instance of ToolsApi' do
      expect(@api_instance).to be_instance_of(AssemblyRuby::ToolsApi)
    end
  end

  # unit tests for health_check
  # Health check
  # Displays a health check of the Assembly service.
  # @param [Hash] opts the optional parameters
  # @return [ToolsStatus]
  describe 'health_check test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
