=begin
#Assembly API

#Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.

The version of the OpenAPI document: 2.0
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AssemblyRuby::SingleCallbackResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AssemblyRuby::SingleCallbackResponse do
  let(:instance) { AssemblyRuby::SingleCallbackResponse.new }

  describe 'test an instance of SingleCallbackResponse' do
    it 'should create an instance of SingleCallbackResponse' do
      expect(instance).to be_instance_of(AssemblyRuby::SingleCallbackResponse)
    end
  end
  describe 'test attribute "call_responses"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
