=begin
#Assembly API

#Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.

The version of the OpenAPI document: 2.0
Contact: support@assemblypayments.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'cgi'

module AssemblyRuby
  class DirectDebitAuthoritiesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create Direct Debit Authority
    # Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
    # @param direct_debit_authority_request_body [DirectDebitAuthorityRequestBody] 
    # @param [Hash] opts the optional parameters
    # @return [SingleDirectDebitAuthority]
    def create_direct_debit_authority(direct_debit_authority_request_body, opts = {})
      data, _status_code, _headers = create_direct_debit_authority_with_http_info(direct_debit_authority_request_body, opts)
      data
    end

    # Create Direct Debit Authority
    # Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
    # @param direct_debit_authority_request_body [DirectDebitAuthorityRequestBody] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(SingleDirectDebitAuthority, Integer, Hash)>] SingleDirectDebitAuthority data, response status code and response headers
    def create_direct_debit_authority_with_http_info(direct_debit_authority_request_body, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DirectDebitAuthoritiesApi.create_direct_debit_authority ...'
      end
      # verify the required parameter 'direct_debit_authority_request_body' is set
      if @api_client.config.client_side_validation && direct_debit_authority_request_body.nil?
        fail ArgumentError, "Missing the required parameter 'direct_debit_authority_request_body' when calling DirectDebitAuthoritiesApi.create_direct_debit_authority"
      end
      # resource path
      local_var_path = '/direct_debit_authorities'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] || @api_client.object_to_http_body(direct_debit_authority_request_body) 

      # return_type
      return_type = opts[:return_type] || 'SingleDirectDebitAuthority' 

      # auth_names
      auth_names = opts[:auth_names] || ['basicAuth', 'oAuth2ClientCredentials']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DirectDebitAuthoritiesApi#create_direct_debit_authority\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List Direct Debit Authorities
    # Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
    # @param account_id [String] Bank account ID
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of records to retrieve. Up to 200. (default to 10)
    # @option opts [Integer] :offset Number of records to offset. Required for pagination. (default to 0)
    # @return [ListDirectDebitAuthorities]
    def list_direct_debit_authorities(account_id, opts = {})
      data, _status_code, _headers = list_direct_debit_authorities_with_http_info(account_id, opts)
      data
    end

    # List Direct Debit Authorities
    # Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
    # @param account_id [String] Bank account ID
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of records to retrieve. Up to 200.
    # @option opts [Integer] :offset Number of records to offset. Required for pagination.
    # @return [Array<(ListDirectDebitAuthorities, Integer, Hash)>] ListDirectDebitAuthorities data, response status code and response headers
    def list_direct_debit_authorities_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DirectDebitAuthoritiesApi.list_direct_debit_authorities ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling DirectDebitAuthoritiesApi.list_direct_debit_authorities"
      end
      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] > 200
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling DirectDebitAuthoritiesApi.list_direct_debit_authorities, must be smaller than or equal to 200.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] < 1
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling DirectDebitAuthoritiesApi.list_direct_debit_authorities, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'offset'].nil? && opts[:'offset'] < 0
        fail ArgumentError, 'invalid value for "opts[:"offset"]" when calling DirectDebitAuthoritiesApi.list_direct_debit_authorities, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = '/direct_debit_authorities'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'account_id'] = account_id
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      # return_type
      return_type = opts[:return_type] || 'ListDirectDebitAuthorities' 

      # auth_names
      auth_names = opts[:auth_names] || ['basicAuth', 'oAuth2ClientCredentials']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DirectDebitAuthoritiesApi#list_direct_debit_authorities\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Show Direct Debit Authority
    # Show details of a specific **Direct Debit Authority** using a given `:id`.
    # @param id [String] Direct debit authority ID
    # @param [Hash] opts the optional parameters
    # @return [SingleDirectDebitAuthority]
    def show_direct_debit_authority(id, opts = {})
      data, _status_code, _headers = show_direct_debit_authority_with_http_info(id, opts)
      data
    end

    # Show Direct Debit Authority
    # Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
    # @param id [String] Direct debit authority ID
    # @param [Hash] opts the optional parameters
    # @return [Array<(SingleDirectDebitAuthority, Integer, Hash)>] SingleDirectDebitAuthority data, response status code and response headers
    def show_direct_debit_authority_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DirectDebitAuthoritiesApi.show_direct_debit_authority ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling DirectDebitAuthoritiesApi.show_direct_debit_authority"
      end
      # resource path
      local_var_path = '/direct_debit_authorities/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      # return_type
      return_type = opts[:return_type] || 'SingleDirectDebitAuthority' 

      # auth_names
      auth_names = opts[:auth_names] || ['basicAuth', 'oAuth2ClientCredentials']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DirectDebitAuthoritiesApi#show_direct_debit_authority\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
